### ISSUE TITLE
Error on Android 4.4.2 (Lenovo A5000, Lenovo A7600-H)

### ISSUE THREAD

**Issue by alario01** [myTargetSDK/mytarget-android#2]
Ошибка на некоторых устройствах, подскажите пож-та в чем может быть дело
```
java.lang.VerifyError: com/my/target/am
	at com.my.target.bb.<init>(NativeAdEngine.java:64)
	at com.my.target.bb.a(NativeAdEngine.java:33)
	at com.my.target.nativeads.NativeAd.handleResult(NativeAd.java:192)
	at com.my.target.nativeads.NativeAd.access$000(NativeAd.java:33)
	at com.my.target.nativeads.NativeAd$1.onResult(NativeAd.java:114)
	at com.my.target.nativeads.NativeAd$1.onResult(NativeAd.java:110)
	at com.my.target.b$2.run(AdFactory.java:191)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5333)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
	at dalvik.system.NativeStart.main(Native Method)
```
<details>
main
  | prio=5
  | tid=1
  | group="main"
  | state=4294967295

AdWorker(Default) #3
  | prio=5
  | tid=3122
  | group="main"
  | state=3
at java.lang.Object.wait(Native Method)
at java.lang.Thread.parkFor(Thread.java:1205)
at sun.misc.Unsafe.park(Unsafe.java:325)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:427)
at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:331)
at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:893)
at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)

AdWorker(Default) #4
  | prio=5
  | tid=3123
  | group="main"
  | state=3
at java.lang.Object.wait(Native Method)
at java.lang.Thread.parkFor(Thread.java:1205)
at sun.misc.Unsafe.park(Unsafe.java:325)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:427)
at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:331)
at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:893)
at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)

AdWorker(NG) #1
  | prio=5
  | tid=3131
  | group="main"
  | state=4
at java.lang.Object.wait(Native Method)
at java.lang.Thread.parkFor(Thread.java:1205)
at sun.misc.Unsafe.park(Unsafe.java:325)
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:197)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2056)
at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1062)
at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:778)
at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)

AudioTrack
  | prio=10
  | tid=3062
  | group="main"
  | state=1
at dalvik.system.NativeStart.run(Native Method)

Binder_1
  | prio=5
  | tid=3048
  | group="main"
  | state=1
at dalvik.system.NativeStart.run(Native Method)

Binder_2
  | prio=5
  | tid=3049
  | group="main"
  | state=1
at dalvik.system.NativeStart.run(Native Method)

Binder_3
  | prio=5
  | tid=3059
  | group="main"
  | state=1
at dalvik.system.NativeStart.run(Native Method)

CleanupReference
  | prio=5
  | tid=3139
  | group="main"
  | state=3
at java.lang.Object.wait(Native Method)
at java.lang.Object.wait(Object.java:401)
at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:102)
at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:73)
at com.android.org.chromium.content.common.CleanupReference$1.run(CleanupReference.java:48)

Compiler
  | prio=5
  | tid=3044
  | group="system"
  | state=3
at dalvik.system.NativeStart.run(Native Method)

CookieSyncManager
  | prio=5
  | tid=3130
  | group="main"
  | state=1
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:138)
at android.os.Looper.loop(Looper.java:150)
at android.webkit.WebSyncManager.run(WebSyncManager.java:89)
at android.webkit.CookieSyncManager.run(CookieSyncManager.java:58)
at java.lang.Thread.run(Thread.java:841)

FMODAudioDevice
  | prio=10
  | tid=3061
  | group="main"
  | state=1
at android.media.AudioTrack.native_write_byte(Native Method)
at android.media.AudioTrack.write(AudioTrack.java:1083)
at org.fmod.FMODAudioDevice.run()
at java.lang.Thread.run(Thread.java:841)

FinalizerDaemon
  | prio=5
  | tid=3046
  | group="system"
  | state=3
at java.lang.Object.wait(Native Method)
at java.lang.Object.wait(Object.java:401)
at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:102)
at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:73)
at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:175)
at java.lang.Thread.run(Thread.java:841)

FinalizerWatchdogDaemon
  | prio=5
  | tid=3047
  | group="system"
  | state=4
at java.lang.VMThread.sleep(Native Method)
at java.lang.Thread.sleep(Thread.java:1013)
at java.lang.Thread.sleep(Thread.java:995)
at java.lang.Daemons$FinalizerWatchdogDaemon.sleepFor(Daemons.java:252)
at java.lang.Daemons$FinalizerWatchdogDaemon.waitForFinalization(Daemons.java:264)
at java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:216)
at java.lang.Thread.run(Thread.java:841)

FirebaseInstanceId
  | prio=5
  | tid=3092
  | group="main"
  | state=3
at java.lang.Object.wait(Native Method)
at java.lang.Thread.parkFor(Thread.java:1205)
at sun.misc.Unsafe.park(Unsafe.java:325)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2017)
at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1050)
at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:778)
at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at com.google.android.gms.common.util.concurrent.zza.run()
at java.lang.Thread.run(Thread.java:841)

GC
  | prio=5
  | tid=3042
  | group="system"
  | state=3
at dalvik.system.NativeStart.run(Native Method)

JavaBridge
  | prio=5
  | tid=3141
  | group="main"
  | state=1
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:138)
at android.os.Looper.loop(Looper.java:150)
at android.os.HandlerThread.run(HandlerThread.java:61)

LooperProvider
  | prio=5
  | tid=3121
  | group="main"
  | state=1
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:138)
at android.os.Looper.loop(Looper.java:150)
at android.os.HandlerThread.run(HandlerThread.java:61)

Measurement Worker
  | prio=5
  | tid=3053
  | group="main"
  | state=4
at java.lang.Object.wait(Native Method)
at java.lang.Object.wait(Object.java:401)
at com.google.android.gms.measurement.internal.zzfk.run(com.google.android.gms:play-services-measurement-impl@@17.0.1:24)

MessengerIpcClient
  | prio=5
  | tid=3094
  | group="main"
  | state=3
at java.lang.Object.wait(Native Method)
at java.lang.Thread.parkFor(Thread.java:1205)
at sun.misc.Unsafe.park(Unsafe.java:325)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2017)
at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1050)
at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:778)
at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at com.google.android.gms.common.util.concurrent.zza.run()
at java.lang.Thread.run(Thread.java:841)

OkHttp ConnectionPool
  | prio=5
  | tid=3152
  | group="main"
  | state=4
at java.lang.Object.wait(Native Method)
at java.lang.Thread.parkFor(Thread.java:1205)
at sun.misc.Unsafe.park(Unsafe.java:325)
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:197)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2056)
at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:435)
at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)

ReferenceQueueDaemon
  | prio=5
  | tid=3045
  | group="system"
  | state=3
at java.lang.Object.wait(Native Method)
at java.lang.Object.wait(Object.java:364)
at java.lang.Daemons$ReferenceQueueDaemon.run(Daemons.java:135)
at java.lang.Thread.run(Thread.java:841)

Signal Catcher
  | prio=5
  | tid=3043
  | group="system"
  | state=3
at dalvik.system.NativeStart.run(Native Method)

Thread-3090
  | prio=5
  | tid=3090
  | group="main"
  | state=1
at dalvik.system.NativeStart.run(Native Method)

Thread-3135
  | prio=5
  | tid=3135
  | group="main"
  | state=1
at dalvik.system.NativeStart.run(Native Method)

Thread-3137
  | prio=5
  | tid=3137
  | group="main"
  | state=1
at dalvik.system.NativeStart.run(Native Method)

Thread-3142
  | prio=5
  | tid=3142
  | group="main"
  | state=1
at dalvik.system.NativeStart.run(Native Method)

Thread-3143
  | prio=4
  | tid=3143
  | group="main"
  | state=1
at dalvik.system.NativeStart.run(Native Method)

Thread-3144
  | prio=4
  | tid=3144
  | group="main"
  | state=1
at dalvik.system.NativeStart.run(Native Method)

Thread-3145
  | prio=5
  | tid=3145
  | group="main"
  | state=3
at java.lang.Object.wait(Native Method)
at java.lang.Thread.parkFor(Thread.java:1205)
at sun.misc.Unsafe.park(Unsafe.java:325)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2017)
at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:510)
at com.google.android.gms.internal.ads.zzc.processRequest(com.google.android.gms:play-services-ads@@18.1.1:23)
at com.google.android.gms.internal.ads.zzc.run(com.google.android.gms:play-services-ads@@18.1.1:15)

Thread-3146
  | prio=5
  | tid=3146
  | group="main"
  | state=3
at java.lang.Object.wait(Native Method)
at java.lang.Thread.parkFor(Thread.java:1205)
at sun.misc.Unsafe.park(Unsafe.java:325)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2017)
at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:510)
at com.google.android.gms.internal.ads.zzm.processRequest(com.google.android.gms:play-services-ads@@18.1.1:20)
at com.google.android.gms.internal.ads.zzm.run(com.google.android.gms:play-services-ads@@18.1.1:12)

Thread-3147
  | prio=5
  | tid=3147
  | group="main"
  | state=3
at java.lang.Object.wait(Native Method)
at java.lang.Thread.parkFor(Thread.java:1205)
at sun.misc.Unsafe.park(Unsafe.java:325)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2017)
at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:510)
at com.google.android.gms.internal.ads.zzm.processRequest(com.google.android.gms:play-services-ads@@18.1.1:20)
at com.google.android.gms.internal.ads.zzm.run(com.google.android.gms:play-services-ads@@18.1.1:12)

Thread-3148
  | prio=5
  | tid=3148
  | group="main"
  | state=3
at java.lang.Object.wait(Native Method)
at java.lang.Thread.parkFor(Thread.java:1205)
at sun.misc.Unsafe.park(Unsafe.java:325)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2017)
at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:510)
at com.google.android.gms.internal.ads.zzm.processRequest(com.google.android.gms:play-services-ads@@18.1.1:20)
at com.google.android.gms.internal.ads.zzm.run(com.google.android.gms:play-services-ads@@18.1.1:12)

Thread-3149
  | prio=5
  | tid=3149
  | group="main"
  | state=3
at java.lang.Object.wait(Native Method)
at java.lang.Thread.parkFor(Thread.java:1205)
at sun.misc.Unsafe.park(Unsafe.java:325)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2017)
at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:510)
at com.google.android.gms.internal.ads.zzm.processRequest(com.google.android.gms:play-services-ads@@18.1.1:20)
at com.google.android.gms.internal.ads.zzm.run(com.google.android.gms:play-services-ads@@18.1.1:12)

Thread-3150
  | prio=5
  | tid=3150
  | group="main"
  | state=1
at dalvik.system.NativeStart.run(Native Method)

Thread-3153
  | prio=5
  | tid=3153
  | group="main"
  | state=1
at dalvik.system.NativeStart.run(Native Method)

UnityChoreographer
  | prio=5
  | tid=3084
  | group="main"
  | state=1
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:138)
at android.os.Looper.loop(Looper.java:150)
at android.os.HandlerThread.run(HandlerThread.java:61)

UnityMain
  | prio=5
  | tid=3057
  | group="main"
  | state=1
at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
at com.unity3d.player.UnityPlayer.c()
at com.unity3d.player.UnityPlayer$e$1.handleMessage()
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at com.unity3d.player.UnityPlayer$e.run()

YMM-APT-1
  | prio=5
  | tid=3063
  | group="main"
  | state=1
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:138)
at android.os.Looper.loop(Looper.java:150)
at android.os.HandlerThread.run(HandlerThread.java:61)

YMM-BD-4
  | prio=5
  | tid=3082
  | group="main"
  | state=3
at java.lang.Object.wait(Native Method)
at java.lang.Thread.parkFor(Thread.java:1205)
at sun.misc.Unsafe.park(Unsafe.java:325)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2017)
at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
at com.yandex.metrica.impl.ob.cn$1.run(SourceFile:93)
at java.lang.Thread.run(Thread.java:841)

YMM-DW-2
  | prio=5
  | tid=3080
  | group="main"
  | state=3
at java.lang.Object.wait(Native Method)
at java.lang.Object.wait(Object.java:364)
at com.yandex.metrica.impl.ob.jq$a.run(SourceFile:84)

YMM-RS-5
  | prio=5
  | tid=3083
  | group="main"
  | state=1
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:138)
at android.os.Looper.loop(Looper.java:150)
at android.os.HandlerThread.run(HandlerThread.java:61)

YMM-YM-3
  | prio=5
  | tid=3081
  | group="main"
  | state=1
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:138)
at android.os.Looper.loop(Looper.java:150)
at android.os.HandlerThread.run(HandlerThread.java:61)

gads-1
  | prio=5
  | tid=3118
  | group="main"
  | state=4
at java.lang.Object.wait(Native Method)
at java.lang.Thread.parkFor(Thread.java:1205)
at sun.misc.Unsafe.park(Unsafe.java:325)
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:197)
at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:429)
at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:331)
at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:910)
at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)

gads-2
  | prio=5
  | tid=3132
  | group="main"
  | state=4
at java.lang.Object.wait(Native Method)
at java.lang.Thread.parkFor(Thread.java:1205)
at sun.misc.Unsafe.park(Unsafe.java:325)
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:197)
at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:429)
at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:331)
at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:910)
at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)

java.lang.ProcessManager
  | prio=5
  | tid=3158
  | group="main"
  | state=3
at java.lang.Object.wait(Native Method)
at java.lang.Object.wait(Object.java:364)
at java.lang.ProcessManager.waitForMoreChildren(ProcessManager.java:140)
at java.lang.ProcessManager.watchChildren(ProcessManager.java:105)
at java.lang.ProcessManager.access$000(ProcessManager.java:40)
at java.lang.ProcessManager$1.run(ProcessManager.java:58)

pool-1-thread-1
  | prio=5
  | tid=3052
  | group="main"
  | state=3
at java.lang.Object.wait(Native Method)
at java.lang.Thread.parkFor(Thread.java:1205)
at sun.misc.Unsafe.park(Unsafe.java:325)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2017)
at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)

pool-8-thread-1
  | prio=5
  | tid=3156
  | group="main"
  | state=3
at java.lang.Object.wait(Native Method)
at java.lang.Thread.parkFor(Thread.java:1205)
at sun.misc.Unsafe.park(Unsafe.java:325)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2017)
at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)

pool-9-thread-1
  | prio=5
  | tid=3157
  | group="main"
  | state=3
at java.lang.Object.wait(Native Method)
at java.lang.Thread.parkFor(Thread.java:1205)
at sun.misc.Unsafe.park(Unsafe.java:325)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2017)
at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
</details>

**Comment by alexskobozev** [comment]
Укажите версию SDK, пожалуйста

**Comment by alario01** [comment]
5.4.7

**Comment by alario01** [comment]
перед крешем еще есть эти ошибки

```
09/26 12:10:16.244 13909 13909 Error dalvikvm: Could not find class 'com.my.target.nativeads.views.PromoCardRecyclerView', referenced from method com.my.target.am.a
```

```
09/26 12:10:16.244 13909 13909 Error dalvikvm: Could not find class 'com.my.target.nativeads.views.PromoCardRecyclerView', referenced from method com.my.target.am.a
```

**Comment by alexskobozev** [comment]
Очевидно, эти классы присутствуют в jar 5.4.7. Вы используете proguard или R8?

**Comment by alario01** [comment]
Proguard

**Comment by alexskobozev** [comment]
Пришлите пожалуйста apk или ссылку на play, посмотрим

**Comment by alario01** [comment]
Проблема решилась после включения multiDex
