### ISSUE TITLE
NullPointerException on startup in 5.6.3(Meizu devices)

### ISSUE THREAD

**Issue by Artemych** [myTargetSDK/mytarget-android#8]
On startup we have a crash on Meizu devices(Android 7). 

Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
       at android.os.Parcel.readException(Parcel.java:1697)
       at android.os.Parcel.readException(Parcel.java:1644)
       at android.location.ILocationManager$Stub$Proxy.getLastLocation(ILocationManager.java:754)
       at android.location.LocationManager.getLastKnownLocation(LocationManager.java:1230)
       at com.my.target.fk.a(fk.java:150)
       at com.my.target.fk.y(fk.java:117)
       at com.my.target.fk.a(fk.java:53)
       at com.my.target.fk$1.run(fk.java:103)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)

**Comment by alexskobozev** [comment]
Hello! Version 5.6.3 is outdated. Please update to current  version (5.11.4 at the moment). This crash is fixed in current versions
